version: "3"
services:
  ddagent:
    image: datadog/agent
    container_name: datadog-agent
    environment:
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY=<YOUR-API-KEY>
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE="name:datadog-agent"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw 
    ports:
      - "8126:8126"
  app:
    container_name: app-2
    restart: always
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - ddagent
  mongo:
    container_name: mongo
    image: mongo
#    volumes:
#      - ./data/db:/data/db
    ports:
      - "27017:27017"
